[package]
name = "survival-rogue-like"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy_asset_loader = "0.14.1"
ron = "0.7.0"
serde = "1.0.136"
serde_with = "2.1.0"
rand = "0.8.5"
bevy_ecs_tilemap = "0.9.0"
noise = "0.8.2"
bevy-inspector-egui = "0.14"
bevy_pkv = "0.6"
serde_json = "1.0"
strum = "^0.15"
strum_macros = "^0.15"
bevy_rapier2d = {version = "0.19.0", features = ["simd-stable","debug-render","parallel"]  }
bevy_pixel_camera = "0.3"
bevy_tweening = "0.6"
interpolation = "0.2.0"
lazy_static = "1.4.0"