[package]
name = "survival-rogue-like"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9.1", default-features = false, features = ["bevy_asset", "bevy_render", "bevy_winit", "filesystem_watcher", "png"]}
bevy_asset_loader = "0.14.1"
ron = "0.7.0"
serde = "1.0.136"
rand = "0.8.5"
bevy_ecs_tilemap = "0.9.0"
noise = "0.8.2"
bevy_pkv = "0.6"
serde_json = "1.0"
anyhow = "1.0.68"
bevy_egui = { version = "0.18.0", default-features = false }
bevy-inspector-egui = "0.15.0"
egui = { version = "0.20.1", features = ["bytemuck"] }
encase = "0.4.1"
log = "0.4.17"
